# Generated by Django 2.2 on 2019-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0003_auto_20190814_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(choices=[('UPEXP', 'UPEXP'), ('UPSAR', 'UPSAR'), ('UPSBL', 'UPSBL'), ('UPSCN', 'UPSCN'), ('UPSGR', 'UPSGR'), ('UPSRD', 'UPSRD'), ('UPSRS', 'UPSRS'), ('UPSSV', 'UPSSV'), ('UPSWX', 'UPSWX'), ('UPS2A', 'UPS2A'), ('UPS3D', 'UPS3D'), ('FX2DY', 'FX2DY'), ('FXSTD', 'FXSTD'), ('FXPAM', 'FXPAM'), ('FXGRN', 'FXGRN'), ('FXFNL', 'FXFNL'), ('Customer Pickup', 'Customer Pickup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(choices=[('American Woodmark Corporation', 'American Woodmark Corporation'), ('ACP', 'ACP'), ('Jim Bishop', 'Jim Bishop'), ('Fabritec', 'Fabritec'), ('Hanssem', 'Hanssem'), ('KabinArt', 'KabinArt'), ('Legacy', 'Legacy'), ('MasterBrand Cabinets, Inc', 'MasterBrand Cabinets, Inc'), ('Unicor', 'Unicor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reason',
            field=models.CharField(choices=[('New Product', 'New Product'), ('Not Applicable', 'Not Applicable'), ('Unusual Size', 'Unusual Size'), ('Unusual Profile', 'Unusual Profile'), ('Unusual Material', 'Unusual Material'), ('Obsolete Product', 'Obsolete Product'), ('Non-Existing Material Specification', 'Non-Existing Material Specification'), ('Customer Sample', 'Customer Sample'), ('Special Assembly', 'Special Assembly'), ('Special Inspection', 'Special Inspection'), ('Special Packaging', 'Special Packaging'), ('Profile Testing', 'Profile Testing'), ('Process Testing', 'Process Testing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tooling_status',
            field=models.CharField(choices=[('On Floor', 'On Floor'), ('In Grinding Room', 'In Grinding Room'), ('Other - See Notes', 'Other - See Notes')], max_length=20),
        ),
    ]
